In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('../Level1 Task2_EDA/Amazon Sale Report.csv', low_memory=False)

print("Shape:", df.shape)
print("\nFirst look:")
df.head()

Shape: (128975, 24)

First look:

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [3]:
# ── 2. Inspect the Data ──────────────────────────────────────
print("Column names:\n", df.columns.tolist())
print("\nData types:\n", df.dtypes)
print("\nMissing values:\n", df.isnull().sum())

Column names:
 ['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ', 'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN', 'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city', 'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids', 'B2B', 'fulfilled-by', 'Unnamed: 22']

Data types:
 index                   int64
Order ID                  str
Date                      str
Status                    str
Fulfilment                str
Sales Channel             str
ship-service-level        str
Style                     str
SKU                       str
Category                  str
Size                      str
ASIN                      str
Courier Status            str
Qty                     int64
currency                  str
Amount                float64
ship-city                 str
ship-state                str
ship-postal-code      float64
ship-country              str
promotion-ids             str
B2B                      bool
fulfilled-by              str
Unnamed: 22            object
dtype: object

Missing values:
 index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

In [4]:
# ── 3. Handle Missing Values ──────────────────────────────────

# Drop columns with more than 50% missing or useless columns
df.drop(columns=['fulfilled-by', 'Unnamed: 22', 'promotion-ids'], inplace=True)
print("Columns after dropping high-missing cols:", df.shape)

# Fill Courier Status with mode
df['Courier Status'].fillna(df['Courier Status'].mode()[0], inplace=True)

# Fill currency with mode
df['currency'].fillna(df['currency'].mode()[0], inplace=True)

# Fill Amount with median
df['Amount'].fillna(df['Amount'].median(), inplace=True)

# Fill ship location columns with 'Unknown'
for col in ['ship-city', 'ship-state', 'ship-postal-code', 'ship-country']:
    df[col].fillna('Unknown', inplace=True)

print("\nMissing values after cleaning:")
print(df.isnull().sum())

Columns after dropping high-missing cols: (128975, 21)

C:\Users\valni\AppData\Local\Temp\ipykernel_17172\3656845924.py:8: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Courier Status'].fillna(df['Courier Status'].mode()[0], inplace=True)
C:\Users\valni\AppData\Local\Temp\ipykernel_17172\3656845924.py:11: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['currency'].fillna(df['currency'].mode()[0], inplace=True)
C:\Users\valni\AppData\Local\Temp\ipykernel_17172\3656845924.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Amount'].fillna(df['Amount'].median(), inplace=True)
C:\Users\valni\AppData\Local\Temp\ipykernel_17172\3656845924.py:18: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna('Unknown', inplace=True)

TypeError: Invalid value 'Unknown' for dtype 'float64'

In [5]:
# ── 3. Handle Missing Values ──────────────────────────────────

# Drop columns with more than 50% missing or useless columns
df.drop(columns=['fulfilled-by', 'Unnamed: 22', 'promotion-ids'], inplace=True)
print("Columns after dropping high-missing cols:", df.shape)

# Fill Courier Status with mode
df['Courier Status'] = df['Courier Status'].fillna(df['Courier Status'].mode()[0])

# Fill currency with mode
df['currency'] = df['currency'].fillna(df['currency'].mode()[0])

# Fill Amount with median
df['Amount'] = df['Amount'].fillna(df['Amount'].median())

# Fill ship location columns with 0 (they are numeric)
for col in ['ship-city', 'ship-state', 'ship-postal-code', 'ship-country']:
    df[col] = df[col].fillna('Unknown').astype(str)

print("\nMissing values after cleaning:")
print(df.isnull().sum())

KeyError: "['fulfilled-by', 'Unnamed: 22', 'promotion-ids'] not found in axis"

In [6]:
# ── 3. Handle Missing Values ──────────────────────────────────

# Drop columns with more than 50% missing (use errors='ignore' in case already dropped)
cols_to_drop = ['fulfilled-by', 'Unnamed: 22', 'promotion-ids']
df = df.drop(columns=[c for c in cols_to_drop if c in df.columns])
print("Columns after dropping:", df.shape)

# Fill Courier Status with mode
df['Courier Status'] = df['Courier Status'].fillna(df['Courier Status'].mode()[0])

# Fill currency with mode
df['currency'] = df['currency'].fillna(df['currency'].mode()[0])

# Fill Amount with median
df['Amount'] = df['Amount'].fillna(df['Amount'].median())

# Fill ship location columns
for col in ['ship-city', 'ship-state', 'ship-postal-code', 'ship-country']:
    df[col] = df[col].astype(str).fillna('Unknown')

print("\nMissing values after cleaning:")
print(df.isnull().sum())

Columns after dropping: (128975, 21)

Missing values after cleaning:
index                 0
Order ID              0
Date                  0
Status                0
Fulfilment            0
Sales Channel         0
ship-service-level    0
Style                 0
SKU                   0
Category              0
Size                  0
ASIN                  0
Courier Status        0
Qty                   0
currency              0
Amount                0
ship-city             0
ship-state            0
ship-postal-code      0
ship-country          0
B2B                   0
dtype: int64

In [7]:
# ── 4. Remove Duplicates ──────────────────────────────────────
print("Duplicates before:", df.duplicated().sum())
df = df.drop_duplicates()
print("Duplicates after:", df.duplicated().sum())
print("New shape:", df.shape)

Duplicates before: 0
Duplicates after: 0
New shape: (128975, 21)

In [8]:
# ── 5. Standardize Data Formats ──────────────────────────────
# Convert Date to datetime
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')

# Standardize categorical columns
cat_cols = ['Status', 'Fulfilment', 'Sales Channel', 'ship-service-level',
            'Category', 'Size', 'Courier Status']

for col in cat_cols:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip().str.title()

print("Date sample:", df['Date'].head())
print("\nStatus values:", df['Status'].unique())
print("\nCategory values:", df['Category'].unique())

C:\Users\valni\AppData\Local\Temp\ipykernel_17172\2757497367.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')

Date sample: 0   2022-04-30
1   2022-04-30
2   2022-04-30
3   2022-04-30
4   2022-04-30
Name: Date, dtype: datetime64[us]

Status values: <StringArray>
[                    'Cancelled',  'Shipped - Delivered To Buyer',
                       'Shipped',  'Shipped - Returned To Seller',
   'Shipped - Rejected By Buyer',     'Shipped - Lost In Transit',
    'Shipped - Out For Delivery', 'Shipped - Returning To Seller',
           'Shipped - Picked Up',                       'Pending',
 'Pending - Waiting For Pick Up',             'Shipped - Damaged',
                      'Shipping']
Length: 13, dtype: str

Category values: <StringArray>
[          'Set',         'Kurta', 'Western Dress',           'Top',
  'Ethnic Dress',        'Bottom',         'Saree',        'Blouse',
       'Dupatta']
Length: 9, dtype: str

In [9]:
# ── 6. Save Cleaned Dataset ──────────────────────────────────
df.to_csv('Amazon_Sales_Cleaned.csv', index=False)
print("Cleaned dataset saved.")
print("Final shape:", df.shape)
df.head()

Cleaned dataset saved.
Final shape: (128975, 21)

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,ASIN,Courier Status,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B
0,0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,B09KXVBD7Z,Shipped,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,False
1,1,171-9198151-1101146,2022-04-30,Shipped - Delivered To Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,Kurta,...,B09K3WFS32,Shipped,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,False
2,2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,Kurta,...,B07WV4JV4D,Shipped,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,True
3,3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,B099NRCT7B,Shipped,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,False
4,4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,B098714BZP,Shipped,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,False